### ISSUE TITLE
copy: copying to / produces error

### ISSUE THREAD

**Issue by ericchiang** [appc/acbuild#130]
I have a tar of a root file system I'd like to use as my base when constructing an ACI. However the command `acbuild copy <src> /` produces an error.

```
$ mkdir rootfs
$ sudo tar -xv rootfs.tar -C rootfs
$ sudo acbuild begin
$ sudo acbuild copy rootfs /
copy: mkdir .acbuild/currentaci/rootfs: file exists
```

Current workaround is to remove `.acbuild/currentaci/rootfs`

```
$ sudo acbuild begin
$ sudo rm -rf .acbuild/currentaci/rootfs
$ sudo acbuild copy rootfs /
...
```

**Comment by dgonyeo** [comment]
Yeah that's an issue. Shouldn't be hard to fix in acbuild, thanks for reporting this.
