### ISSUE TITLE
systemd-nspawn: Failed to register machine: Machine 'target' already exists

### ISSUE THREAD

**Issue by dgonyeo** [appc/acbuild#131]
systemd-nspawn determines the machine's name to enter in to machinectl via the target directory to chroot into. This directory is always named `target` by acbuild, thus every container acbuild starts up is called `target`. This means that multiple `acbuild run` invocations cannot be running at the same time.

`--machine acbuild-<hash-of-path>` flag should be passed to systemd-nspawn to prevent this.

**Comment by jonboulle** [comment]
Why are these getting registered as machines? That doesn't seem right.

Derek Gonyeo <notifications@github.com> schrieb am Fr., 27. Nov. 2015 13:43:

**Comment by dgonyeo** [comment]
That's the default.

```
--register=
           Controls whether the container is registered with systemd-machined(8). Takes a boolean argument, defaults to "yes". ...
```

It might make more sense to just disable registration though.

**Comment by jonboulle** [comment]
Yep

Derek Gonyeo <notifications@github.com> schrieb am Fr., 27. Nov. 2015 15:14:
