### ISSUE TITLE
Release binaries dynamically compiled for NixOS

### ISSUE THREAD

**Issue by namsral** [appc/acbuild#133]
The `acbuild` binaries made available on the github release page fail to run:

    $ curl -s -L -O https://github.com/appc/acbuild/releases/download/v0.2.1/acbuild.tar.gz
    $ tar xzf acbuild.tar.gz 
    $ ./acbuild 
    -bash: ./acbuild: No such file or directory

The release binaries are dynamically compiled and will only run on [Nix](http://nixos.org/) unless you symlink the interpreter. 

    $ file acbuild
    acbuild: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/npfsi1d9ka8zwnxzn3sr08hbwvpapyk7-glibc-2.21/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped

I think it would be more useful to statically compile the binaries.

**Comment by jonboulle** [comment]
```
	/nix/store/npfsi1d9ka8zwnxzn3sr08hbwvpapyk7-glibc-2.21/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x0000562407f91000)
```
gross!

It's unlikely we'll be able to fully statically compile since we need DNS (see e.g. https://github.com/coreos/rkt/pull/1380#issuecomment-140341653), but we should definitely be able to provide a more portable build.

**Comment by dgonyeo** [comment]
My bad, forgot that nixos will result in binaries like that. I'll rebuild the release on a more normal distro.

**Comment by dgonyeo** [comment]
I just uploaded new binaries (still dynamically linked) that were compiled on an x86_64 machine running arch for the releases. Can you verify that the latest release runs on your system now?

I'll look into statically linking things that aren't related to DNS.

**Comment by namsral** [comment]
I can confirm the latest release now runs on my system.

**Comment by jonboulle** [comment]
#86 would mitigate this :-)
