### ISSUE TITLE
acbuild run with systemd-208 fails

### ISSUE THREAD

**Issue by blalor** [appc/acbuild#140]
systemd v208 on CentOS 7.  `acbuild run` fails because this version of `systemd-nspawn` doesn't support the `-q/--quiet` option.

**Comment by dgonyeo** [comment]
That's definitely an issue. I just made a PR that should fix this (https://github.com/appc/acbuild/pull/141), would you be willing to take it for a spin and make sure that this is fixed on your end?

**Comment by blalor** [comment]
@dgonyeo different error, now. :-) 

    systemd-nspawn: unrecognized option '--register=no'

It appears `--register` was also [added in v209](https://github.com/systemd/systemd/commit/eb91eb187b7491e05fb95215b77cb62061f41d08).

**Comment by blalor** [comment]
So, removing `--register` does allow `acbuild run`.  Assuming the behavior in v208 *is* to register the container with machined, I don't know what the impact of that is.

**Comment by ecnahc515** [comment]
@blalor registration isn't really anything important, https://github.com/appc/acbuild/pull/135 removed registration, but it needs to check for the systemd version to ensure that flag is valid to fix this issue. 

I wonder if using nspawn is more effort to maintain than it's worth. Perhaps a pure go implementation for execution would make more sense (something like libcontainer with minimal options perhaps?). Or even running rkt (which I believe bundles systemd).

**Comment by dgonyeo** [comment]
I'd prefer to just get around to https://github.com/appc/acbuild/issues/13, which pretty much addresses this (just with more work than dropping nspawn completely).

**Comment by dgonyeo** [comment]
Just updated the PR for this issue to also not pass `--register` for when systemd < 209.
