### ISSUE TITLE
cache dependencies across acbuild invocations

### ISSUE THREAD

**Issue by blalor** [appc/acbuild#144]
I know this goes against the design goals of acbuild (or at least how I interpret them), but it'd be really nice if `acbuild` could cache dependencies across contexts.  Every time I do `acbuild`, `acbuild dependency add …`, `acbuild run`, `acbuild end`, the dependency gets downloaded, which is much slower than I'd like.

**Comment by iaguis** [comment]
https://github.com/appc/acbuild/issues/125

**Comment by blalor** [comment]
Yep.  Closing.  Thanks!
