### ISSUE TITLE
relative symlink for /etc/localtime causes run to fail

### ISSUE THREAD

**Issue by blalor** [appc/acbuild#145]
host machine: `readlink /etc/localtime -> ../usr/share/zoneinfo/Etc/UTC`

setup:

```
acbuild begin
acbuild dependency add s3.amazonaws.com/bsd-aci/base/centos7 --label version=4b6264c-14
acbuild mount add resolvconf /etc/resolv.conf --read-only
acbuild set-name whatev
acbuild set-exec /bin/bash
acbuild run /bin/true
```

If I run this in `/tmp` it works.  If I run in `/tmp/foo` it fails because `acbuild` resolves the symlink relative to the current directory, rather than to `/etc`:
```
run: open ../usr/share/zoneinfo/Etc/UTC: no such file or directory
```

**Comment by dgonyeo** [comment]
That's interesting. Should be a straightforward fix. Thanks for all these bug reports :)

**Comment by blalor** [comment]
Thanks for fixing ‘em! :-)

**Comment by blalor** [comment]
Submitting a PR for this one.
