### ISSUE TITLE
run: add a flag to set working directory

### ISSUE THREAD

**Issue by dgonyeo** [appc/acbuild#154]
It would be useful if there was a flag to set the working directory for a given `acbuild run` command.

There doesn't appear to be a `systemd-nspawn` flag that can do this, so I imagine that acbuild will need to call some intermediate binary, that will then call the intended binary in the correct directory.

It looks like rkt uses [a c program](https://github.com/coreos/rkt/blob/master/stage1/appexec/appexec.c) to do this, but I'd prefer to not have additional binaries acbuild needs at runtime.

Perhaps acbuild itself could gain this functionality, and when `acbuild run` is called it'll copy itself into the container, run itself with `systemd-nspawn`, and then `os/exec` the intended binary in the correct directory?

**Comment by jonboulle** [comment]
Could always poke upstream to see if they would add a working directory to systemd-nspawn, it's not unreasonable.

**Comment by dgonyeo** [comment]
Looks like upstream added this, so should be easy for us to implement now:
https://github.com/systemd/systemd/issues/2192
