### ISSUE TITLE
begin: starting from tar doesn't create correct directory structure

### ISSUE THREAD

**Issue by ericchiang** [appc/acbuild#156]
```console
$ mkdir foo
$ acbuild begin ./foo
$ ls .acbuild/currentaci/
manifest  rootfs
$ acbuild end
$ tar -cf foo.tar foo
$ acbuild begin ./foo.tar
$ ls .acbuild/currentaci/
foo
$ acbuild set-name foo
set-name: open .acbuild/currentaci/manifest: no such file or directory
```

**Comment by ericchiang** [comment]
It looks like acbuild is treating `foo.tar` like an ACI.

To help identify these issues, can acbuild validate ACIs before unpacking them? 
("ERROR: foo.tar is not a valid ACI")

As for the archive stuff. It would be nice to be able to begin by using a tar as the rootfs. Could acbuild do one of the following?

* Determine if the file is an archive or an ACI based on file extension.
* Add a `--from-archive` flag.

Or I can just keep untaring my files manually and begin from a directory :)

**Comment by dgonyeo** [comment]
Yup, acbuild doesn't currently support starting from a tarball of a rootfs. I'll add support for that, since you're not the only person who's recently run into this.
