### ISSUE TITLE
acbuild exit code always 0

### ISSUE THREAD

**Issue by f0** [appc/acbuild#160]
if a acbuild subcommand failed, the exit code is always 0, but should be > 0

e.g acbuild annotation a $b   <-- add is missed

comes back with $?=0,  so its not possible to check for problems in the build!

**Comment by dgonyeo** [comment]
Yup this is definitely an issue. I've known about it for a little while, but I guess I never made an issue. 

That exit code is coming from cobra, so I'm not positive how to fix it. Worst case scenario we have to modify cobra, but maybe it exposes a way to set the exit code on a failed parse. 

Thanks for reporting this.
