### ISSUE TITLE
can't copy to /

### ISSUE THREAD

**Issue by mischief** [appc/acbuild#163]
copy seems to abort if rootfs already exists when the target is /.

```
mischief@delta /tmp $ mkdir a
mischief@delta /tmp $ acbuild begin
mischief@delta /tmp $ acbuild copy a /
copy: mkdir .acbuild/currentaci/rootfs: file exists
```

**Comment by mischief** [comment]
seems --to-dir fixes this, but the UX here could be improved :-)

**Comment by dgonyeo** [comment]
Yup, `--to-dir` is what you want.

The reasoning for the bizarre UX is that acbuild lazily fetches dependencies, and as such when you call `acbuild copy nginx.conf /etc/nginx`, acbuild doesn't know if the `/etc/nginx` directory exists. For all it knows you want the file `/etc/nginx` inside the container to be a copy of the file `nginx.conf` outside of the container. acbuild could fetch the dependencies for an `acbuild copy` command so it can know if directories exist, but downloading tens to hundreds of megabytes to copy a file into a tarball seems excessive. To make the problem worse, acbuild doesn't currently hold on to dependencies between runs.

One options is that once https://github.com/appc/acbuild/issues/125 is done acbuild could hold on to dependencies between runs, in which case preemptively fetching dependencies will be more reasonable. (I don't have too much faith in the current store logic).

Another option is to remove `acbuild copy` and replace it with `acbuild copy-to-dir` and `acbuild copy-file` or something similar, so the difference is a little more obvious than having it fail on you and needing to dig around for `acbuild copy`'s flags.
