### ISSUE TITLE
Error message unclear: "lacks the binary to execute or doesn't look like a binary tree. Refusing."

### ISSUE THREAD

**Issue by alban** [appc/acbuild#165]
Reported initially in https://github.com/coreos/rkt/issues/2153:

When running `acbuild run /usr/bin/non-existent-program`, the error message is confusing:
"lacks the binary to execute or doesn't look like a binary tree. Refusing."

It comes directly from `systemd-nspawn`. Should `acbuild` checks this before, so that it is more user-friendly?

Same error message in: https://github.com/appc/acbuild/issues/159

/cc @zopyx

**Comment by dgonyeo** [comment]
Should be fairly easy to catch and print a more sensible error.
