### ISSUE TITLE
Recovering from pre-terminated build

### ISSUE THREAD

**Issue by zopyx** [appc/acbuild#167]
I was running a build with several acbuild command. My ssh connection broke within the build.
After re-login I tried to restart the build but it failed with

Beginning build with an empty ACI
begin: build already in progress in this working dir
Setting name of ACI to zopyx/plone
set-name: open .acbuild/currentaci/manifest: no such file or directory
Adding dependency "quay.io/coreos/alpine-sh"
dependency add: open .acbuild/currentaci/manifest: no such file or directory
Running: [apk update]
run: readdirent: no such file or directory

So what is the right way to recover from such a state? Shouldn't  the build process be more stable and dealing better with such situations?

**Comment by dgonyeo** [comment]
The correct way to clean up from an incomplete build is the `acbuild end` command.

Ideally when the connection terminated the bash process would have cleaned up after itself, are you using the [template from the docs](https://github.com/appc/acbuild/blob/master/Documentation/bash-scripts.md)? If you are I guess the `trap ... EXIT` doesn't catch whatever signal bash is sent when the ssh connection is terminated, and that's an issue with the docs and examples.

**Comment by dgonyeo** [comment]
I don't believe there's much I can do for this unless there's a bug in `acbuild end`. I want to revisit https://github.com/appc/acbuild/issues/23 eventually, and if that happens guaranteeing that cleanup happens will be easier (and not relying on the user properly setting up a bash trap).
