### ISSUE TITLE
Recovering from pre-terminated build: device or resource busy

### ISSUE THREAD

**Issue by zopyx** [appc/acbuild#168]
I tried to remove .acbuild because of a pre-terminated build due to a broken SSH connection. This fails:

[root@vmd9666 plone-aci2]#  rm -fr .acbuild/
rm: cannot remove '.acbuild/target': Device or resource busy

Checking the open file handles using lsof did not reveal any process holding a lock on the .acbuild directory.

**Comment by alban** [comment]
Is there any mount points in this directory? Or is `systemd-nspawn` still running in there? Its current working directory might be in there.

**Comment by zopyx** [comment]
What do you mean with mount-points?

```
 [root@vmd9666 ~]# ps auxw|grep syste
root         1  0.0  0.0  43920  5260 ?        Ss   Jan23   1:31
/usr/lib/systemd/systemd --system --deserialize 18
root       439  0.0  1.6 201820 98800 ?        Ss   Jan23   4:38
/usr/lib/systemd/systemd-journald
dbus       560  0.0  0.0  54964  3408 ?        Ss   Jan23   0:43
/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile
--systemd-activation
root       611  0.0  0.0  24844  3124 ?        Ss   Jan23   0:17
/usr/lib/systemd/systemd-logind
plone      633  0.0  0.0  45324  3764 ?        Ss   Jan23   0:03
/usr/lib/systemd/systemd --user
root      2401  0.0  0.0  43208  3872 ?        Ss   Jan26   0:02
/usr/lib/systemd/systemd --user
root     11199  0.0  0.0   9120   952 pts/0    S+   13:10   0:00 grep
--color=auto syste
root     13443  0.0  0.0  17908  2516 ?        Ss   Feb08   0:01
/usr/lib/systemd/systemd-machined
root     32295  0.0  0.0  43328  2876 ?        Ss   Feb08   0:00
/usr/lib/systemd/systemd-udevd
```

**Comment by dgonyeo** [comment]
During a run command acbuild will mount an overlayfs to `.acbuild/target`. It would probably be reasonable for acbuild to see if this is already mounted and try to umount it if it is.

For specifically your case, see if running `umount .acbuild/target` from the directory you ran acbuild in will allow you to delete the `.acbuild` directory.
