### ISSUE TITLE
Unable to stop/break acbuild step

### ISSUE THREAD

**Issue by zopyx** [appc/acbuild#169]
This script

https://github.com/zopyx/plone-aci/blob/master/plone.sh

runs a small bash script

https://github.com/zopyx/plone-aci/blob/master/build.sh

which will perform the installation of the CMS Plone.

It is not possible to break the 

bin/buildout

execution using Ctrl-C or Ctrl-Z

What is the recommended way to break an script running acbuild steps in a sane way without corruption.

**Comment by dgonyeo** [comment]
While in the middle of an `acbuild run` command, you should be able to break out by pressing Ctrl-] three times (this is a systemd-nspawn thing), and while in the middle of any other part of the script you can stop the script with Ctrl-C.

I suppose I should mention this in the documentation :p
