### ISSUE TITLE
begin: image fetching

### ISSUE THREAD

**Issue by dgonyeo** [appc/acbuild#17]
`begin` should support being given an image name instead of a local file as a starting point. acbuild would then download the ACI and use it as the starting point for the new build.

```
acbuild begin quay.io/coreos/alpine-sh
```

**Comment by jonboulle** [comment]
Related: #8

**Comment by jonboulle** [comment]
This is really useful but the exact UX for specifying images becomes complex quickly (coreos/rkt#715). 

For now can we leverage what we do in rkt for this? (discovery, local file, http URL, docker://)

**Comment by jonboulle** [comment]
Workaround right now is using something out-of-band to do discovery and retrieve the ACI manually.
