### ISSUE TITLE
vagrant: switch to using a wily image

### ISSUE THREAD

**Issue by dgonyeo** [appc/acbuild#187]
Apparently ubuntu/vivid64 doesn't exist in some cases. Should switch to using a wily image.

https://github.com/coreos/rkt/issues/2243

**Comment by saintx** [comment]
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/vivid64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'ubuntu/vivid64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/vivid64"]
Error: The requested URL returned error: 404 Not Found
