### ISSUE TITLE
Sign acbuild releases

### ISSUE THREAD

**Issue by brianredbeard** [appc/acbuild#189]
Currently releases of `acbuild` are unsigned.  Please provide detached gpg signatures for them.

**Comment by dgonyeo** [comment]
Do we have a CoreOS signing key for releases, or would just using my key be fine?

**Comment by philips** [comment]
@dgonyeo your key is fine.

**Comment by dgonyeo** [comment]
Latest release is signed: https://github.com/appc/acbuild/releases/tag/v0.3.0

**Comment by dghubble** [comment]
@dgonyeo has your key 0x4AF8D94884580913 been published to a keyserver? The signature won't be useful to verifiers until there is evidence it is controlled by a maintainer. 

Can you also add your pubkey to your Github profile? I find this old key for you which isn't right. https://pgp.mit.edu/pks/lookup?op=vindex&search=0xBB0C07A98BEFE969

**Comment by dgonyeo** [comment]
Ah right, that's important. I just added the key to by github profile and posted it on pgp.mit.edu.

**Comment by dghubble** [comment]
Thank you sir!
