### ISSUE TITLE
wrong arch label generated on arm(v7l)

### ISSUE THREAD

**Issue by godart** [appc/acbuild#190]
Running `actool begin` on a Cubietruck ARMv7 computer fails with:
```
begin: json: error calling MarshalJSON for type types.Labels: bad arch "arm" for linux (must be one of: [amd64 i386 aarch64 aarch64_be armv6l armv7l armv7b])
```
It looks like the label value is generated from GOARCH, but not the architecture name returned by `uname -m`.

**Comment by dgonyeo** [comment]
I guess the correct thing to do here is to add a case to check which arm platform acbuild is running on when GOARCH is set to "arm". I'll see if I can make a PR to do that.
