### ISSUE TITLE
needs update for current spec 0.8.1

### ISSUE THREAD

**Issue by onlyjob** [appc/acbuild#199]
Current release 0.2.2 needs update for compatibility with _appc/spec_ 0.7.4.

**Comment by onlyjob** [comment]
This bug is holding introduction of _acbuild_ package to Debian where _rkt_ is sort of incomplete without _acbuild_...

**Comment by dgonyeo** [comment]
This is fixed in master, so all that needs to be done for this is to cut a release. I'll get that to happen in the next few days at the latest.

**Comment by onlyjob** [comment]
Hi @dgonyeo,

It's been a week + few days... Is there anything that holds new release?
No pressure, just being curious. ;)

**Comment by dgonyeo** [comment]
The only thing holding it up was that school can be rather distracting.

https://github.com/appc/acbuild/pull/204

**Comment by jonboulle** [comment]
now we need an update for spec 0.8.1 :-)

**Comment by onlyjob** [comment]
Is there going to be a tagged release until then?

**Comment by jonboulle** [comment]
Yeah we can tag 0.3.0 in the meantime.

Dmitry Smirnov <notifications@github.com> schrieb am Sa., 14. Mai 2016,
10:23:

**Comment by onlyjob** [comment]
Tagging v0.3.0 would be useful in order to introduce _acbuild_ to Debian....

**Comment by dgonyeo** [comment]
v0.3.0 was just tagged. I'll keep this open as a reminder to bump the appc spec version in the future.

**Comment by onlyjob** [comment]
Ping? Once I upload new specs to Debian it will break _acbuild_ which will become unbuildable hence this issue is effectively blocking upload of new release of _rkt_....

**Comment by dgonyeo** [comment]
I just made this PR: https://github.com/appc/acbuild/pull/214.

Once that gets merged I'll make a v0.3.1 release.

**Comment by dgonyeo** [comment]
And now the latest release of acbuild (v0.3.1) uses version 0.8.4 of the appc spec, the same as rkt v1.8.0.
