### ISSUE TITLE
Use github.com/spf13/cobra CLI library?

### ISSUE THREAD

**Issue by sgotti** [appc/acbuild#2]
Coming from coreos/rkt#1028 starting with a CLI library like it should be useful (see https://github.com/coreos/rkt/issues/632#issuecomment-108904070 for a list of features/requirementd) and avoid additional work now and in the future.

**Comment by jonboulle** [comment]
+1, sgtm

**Comment by dgonyeo** [comment]
Implementation that was just merged uses cobra.
