### ISSUE TITLE
Disable SSL in dep add

### ISSUE THREAD

**Issue by jdu** [appc/acbuild#210]
**acbuild ver**: v0.3.0
**appc version**: 0.7.4

Can an option be added to `acbuild dep add` to use non-SSL URIs for image retrieval? 

If I do:

```
core@core-01 ~ $ sudo acbuild dep add <domain>/base
core@core-01 ~ $ sudo acbuild --debug run -- apk update
Running: [apk update]
```

I get a timeout because my server i've set up isn't running SSL on the domain just yet.

```
run: Get https://<domain>?ac-discovery=1: dial tcp <ip>:443: i/o timeout
```

If I manually specify that I want `http://` I end up with errors because acbuild parses the URI for the image into just being `http`

```
core@core-01 ~ $ sudo acbuild dep add http://<domain>/base
core@core-01 ~ $ sudo acbuild --debug run -- apk update
Running: [apk update]
```

This results in an error because `acbuild` turns the URI into `https://http?ac-discovery=1`

```
run: Get https://http?ac-discovery=1: dial tcp: lookup http: no such host
```

I've tried specifying the dependency URI with different formatting:

```
"http://<domain>/base"
'http://<domain>/base'
http\:\/\/<domain>\/base
```
which doesn't seem to work.

It would be really helpful if there was an arg/command-line flag or the acbuild tool simply understood that if a dependency began with `http://` that SSL shouldn't be used and to use the URI as written.

I know this is a security issue, but the problem is I'm trying to sort out the architecture/build system for an application before I go ahead and purchase resources like SSL and servers, etc... I have the meta discovery HTML and files set up on a localhost in order to test things out and suss out how I'm going to build the system, so it would be really helpful to have a command-line flag so I could write something like this:

```
sudo acbuild dep add --no-ssl <domain>/base
```

And have acbuild resolve the URI as http://<domain>/base or else be able to specify the resource as

```
sudo acbuild dep add http://<domain>/base
``` 

and have acbuild use the resource as written instead of building up the HTTPS route.

**Comment by jdu** [comment]
So after a day of rest, I found the option to retrieve dependencies "insecure" under the `run` command using `--insecure`, this feels wrong from a usage standpoint though. 

It feels like it would make more sense to mark a dependency as insecure at the point where the dependency is added to the build. I know the dependencies are fetched at the first occurence of a `run`

**Comment by dgonyeo** [comment]
Sorry I wasn't able to respond before you had to figure it out on your own.

The UX would definitely be better to specify this at the time the dependency is added. I want to fetch dependencies at the `dep add` step in acbuild, but I don't want to make that switch until acbuild can hold on to dependencies between builds. This shouldn't be too big of a switch to make, so hopefully it won't be too much longer until I sit down and make it happen.

**Comment by jdu** [comment]
Probably the easiest thing to do would be to implement a cache folder somewhere on the system I guess.

But that spins off into adding commands like `acbuild empty-cache` or adding `--no-cache` as an option to `acbuild dep add` to ignore the cache, etc...

I'm only just getting into using Go, otherwise i'd contribute a little more directly, but i'm still very much trying to stuff my python-based brain into the Go mould.
