### ISSUE TITLE
Running commands that contain options

### ISSUE THREAD

**Issue by ae6rt** [appc/acbuild#213]
This may be expected behavior, but I could find no mention of it in the docs.  

This does not work

```
$ acbuild begin
$ acbuild --debug run curl -O http://www.example.com/foo
Error: unknown shorthand flag: 'O' in -O
NAME:
	run - Run a command in an ACI

USAGE:
	acbuild run CMD [ARGS]

EXAMPLE:
	acbuild run yum install nginx

OPTIONS:
      --engine="systemd-nspawn": The engine used to run the command. Supported engines: [systemd-nspawn]
      --insecure[=false]: Allows fetching dependencies over http
      --working-dir="": The working directory inside the container for this command
```
but this does

```
$ sudo acbuild --debug run -- curl -O http://www.example.com/foo
Running: [curl -O http://www.example.com/foo]
...
```

where _--_ is required to apparently terminate options to the run command itself.

I don't know if the _--_ is intentionally required, so I report it as a safety measure. The help offered for the run command doesn't obviously suggest or imply _--_ may be required.

Thanks.

**Comment by dgonyeo** [comment]
Yup, this is an issue with the docs. I'll update the example `acbuild run --help` shows, and make sure the docs in the repo mention this.
