### ISSUE TITLE
release paths

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [appc/acbuild#215]
please use consistent naming pattern for release paths:

compare:
https://github.com/coreos/rkt/releases 
vs 
https://github.com/appc/acbuild/releases

1) have a version in artifact name:
https://github.com/coreos/rkt/releases/download/v1.7.0/rkt-v1.7.0.tar.gz

2) does not have a version in artifact name:
https://github.com/appc/acbuild/releases/download/v0.3.0/acbuild.tar.gz

version is good when you do not want an overwrite on every untar

**Comment by dgonyeo** [comment]
Would simply naming the release artifacts to include the version be sufficient, or do you think also naming the contents inside the tarball to include the version number would be appropriate?

**Comment by Andrei-Pozolotin** [comment]
1) yes:  "inside the tarball to include the version number would be appropriate"

2) `rkt` have established a "standard", other modules must now follow:
https://github.com/coreos/rkt/releases/download/v1.7.0/rkt-v1.7.0.tar.gz

3) it is also not how docker does it, then must be good :-)
https://get.docker.com/builds/Linux/x86_64/docker-1.11.2.tgz

**Comment by dgonyeo** [comment]
The artifact for the most recent release (v0.3.1) follows the format "acbuild-$VERSION.tar.gz" and the acbuild binary inside this artifact is placed in a directory named "acbuild-$VERSION".

Or in other words:
```
derek@proton ~> tar tfv acbuild-v0.3.1.tar.gz 
-rwxr-xr-x root/root  11025984 2016-06-15 15:41 acbuild-v0.3.1/acbuild
```

I'm going to close this issue, if there's something else on this subject that I've missed please feel free to reopen it.

**Comment by Andrei-Pozolotin** [comment]
works, thank you
https://aur.archlinux.org/packages/acbuild/
