### ISSUE TITLE
*: add implicit layered mode

### ISSUE THREAD

**Issue by dgonyeo** [appc/acbuild#22]
A mode should be added where every acbuild command implicitly creates a new layer (akin to how a Dockerfile works). This would probably make the most sense as a flag on the `begin` command.

**Comment by jonboulle** [comment]
I want to push back on this a little - I think the explicit mode (#21) is a much more useful workflow to encourage, and I'd want to hold off on supporting this until/unless there's clear demand for it.

**Comment by dgonyeo** [comment]
I agree. The main reason I had this in here was because it appeared in the initial README (iirc).
