### ISSUE TITLE
Release tarball gzip

### ISSUE THREAD

**Issue by JulienBalestra** [appc/acbuild#233]
Thank you for the project !

Just a small detail about the tarball in the release page:

The extension gave is commonly used for gzip format: acbuild-v0.3.1.tar.gz
But it's only a POSIX tar archive.

```
tar -xzvf acbuild-v0.3.1.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
```
file acbuild-v0.3.1.tar.gz 
acbuild-v0.3.1.tar.gz: POSIX tar archive (GNU)
```

```
tar -xvf acbuild-v0.3.1.tar.gz 
acbuild-v0.3.1/acbuild
```

**Comment by dgonyeo** [comment]
That's weird... not sure how I messed that up. Should be fixed now, and the file is much smaller as a result.
