### ISSUE TITLE
Issue untar'ing some ACIs

### ISSUE THREAD

**Issue by dgonyeo** [appc/acbuild#36]
Certain ACIs cause the following error when acbuild attempts to untar them:
```
extracttar error: exit status 1, output: error extracting tar: error extracting tarball: archive/tar: invalid tar header
```

An example of an ACI that causes this is at https://aci.gonyeo.com/nginx-latest-linux-amd64.aci. The application was made with buildroot, and the ACI was built with actool. rkt has no issues running the ACI.

**Comment by ecnahc515** [comment]
I'm experiencing this with `docker://debian` as well. Converted w/ docker2aci.
