### ISSUE TITLE
begin: error message when local aci path is invalid isn't good

### ISSUE THREAD

**Issue by dgonyeo** [appc/acbuild#49]
If the local file doesn't exist acbuild will attempt to perform meta discovery on the provided start point. This results in misleading error messages when the aci doesn't exist:

```
begin: Get https://beginlocaltest.aci?ac-discovery=1: dial tcp: lookup beginlocaltest.aci on 10.7.2.1:53: no such host
```

**Comment by jonboulle** [comment]
Cross reference: coreos/rkt#715

**Comment by jonboulle** [comment]
@dgonyeo if you figure out a good answer here, let's use it there too ;-)

**Comment by dgonyeo** [comment]
Closed via https://github.com/appc/acbuild/pull/101
