### ISSUE TITLE
Panic while uncompressing dependency

### ISSUE THREAD

**Issue by jcollie** [appc/acbuild#56]
After updating to the lastest master this morning, I started getting the following error:

    [jcollie@pc28043 rkt-logstash]$ acbuild version
    acbuild version v0.1.0-4-g40f07a0
    appc version 0.7.1+git
    [jcollie@pc28043 rkt-logstash]$ sudo acbuild begin
    [jcollie@pc28043 rkt-logstash]$ sudo acbuild dependency add dmacc.net/centos7 --image-id="sha512-baae275b452242b1ccdba64bff15a7a9" --label="version=0.1"
    [jcollie@pc28043 rkt-logstash]$ sudo acbuild label add os linux
    [jcollie@pc28043 rkt-logstash]$ sudo acbuild label add arch amd64
    [jcollie@pc28043 rkt-logstash]$ sudo acbuild run --debug -- yum -y update
    Running: [yum -y update]
    Downloading dmacc.net/centos7: [===============================] 62.9 MB/62.9 MB
    panic: runtime error: makeslice: len out of range==            ] 41.6 MB/62.9 MB
    
    goroutine 1 [running]:
    strings.Repeat(0x8ca320, 0x1, 0xfffffffffffffff5, 0x0, 0x0)
            /usr/local/go/src/strings/strings.go:464 +0x5f
    github.com/appc/acbuild/Godeps/_workspace/src/github.com/coreos/ioprogress.DrawTextFormatBarForW.func2(0x4f38000, 0x3bfe5e9, 0x0, 0x0)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/coreos/ioprogress/draw.go:114 +0xcf
    github.com/appc/acbuild/registry.newIoprogress.func1(0x4f38000, 0x3bfe5e9, 0x0, 0x0)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/registry/fetch.go:441 +0x244
    github.com/appc/acbuild/Godeps/_workspace/src/github.com/coreos/ioprogress.DrawTerminalf.func1(0x4f38000, 0x3bfe5e9, 0x0, 0x0)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/coreos/ioprogress/draw.go:54 +0xf8
    github.com/appc/acbuild/Godeps/_workspace/src/github.com/coreos/ioprogress.(*Reader).drawProgress(0xc820063d10)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/coreos/ioprogress/reader.go:76 +0x1e1
    github.com/appc/acbuild/Godeps/_workspace/src/github.com/coreos/ioprogress.(*Reader).Read(0xc820063d10, 0xc8204c6000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/coreos/ioprogress/reader.go:50 +0x115
    io.copyBuffer(0x7fd0406453f8, 0xc820028228, 0x7fd040647418, 0xc820063d10, 0xc8204c6000, 0x8000, 0x8000, 0x4f30000, 0x0, 0x0)
            /usr/local/go/src/io/io.go:381 +0x247
    io.Copy(0x7fd0406453f8, 0xc820028228, 0x7fd040647418, 0xc820063d10, 0xc820028228, 0x0, 0x0)
            /usr/local/go/src/io/io.go:351 +0x64
    github.com/appc/acbuild/registry.Registry.uncompress(0xc8200f6520, 0x15, 0xc8200f65a0, 0x1a, 0x860100, 0x0, 0x0)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/registry/fetch.go:256 +0x5e2
    github.com/appc/acbuild/registry.Registry.fetchACIWithSize(0xc8200f6520, 0x15, 0xc8200f65a0, 0x1a, 0x430100, 0xc8200f6be0, 0x11, 0xc820085b80, 0x1, 0x4, ...)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/registry/fetch.go:134 +0x556
    github.com/appc/acbuild/registry.Registry.Fetch(0xc8200f6520, 0x15, 0xc8200f65a0, 0x1a, 0x540100, 0xc8200f6be0, 0x11, 0xc820085b80, 0x1, 0x4, ...)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/registry/fetch.go:58 +0x1c9
    github.com/appc/acbuild/registry.Registry.FetchAndRender(0xc8200f6520, 0x15, 0xc8200f65a0, 0x1a, 0x100, 0xc8200f6be0, 0x11, 0xc820085b80, 0x1, 0x4, ...)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/registry/fetch.go:71 +0xf3
    github.com/appc/acbuild/lib.(*ACBuild).renderACI(0xc820085980, 0x100, 0x0, 0x0, 0x0, 0x0, 0x0)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/lib/run.go:200 +0x35c
    github.com/appc/acbuild/lib.(*ACBuild).Run(0xc820085980, 0xc820062fa0, 0x3, 0x5, 0x0, 0x0, 0x0)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/lib/run.go:87 +0x4f1
    main.runRun(0xd19fc0, 0xc820062fa0, 0x3, 0x5, 0x2)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/acbuild/run.go:48 +0x19f
    main.runWrapper.func1(0xd19fc0, 0xc820062fa0, 0x3, 0x5)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/acbuild/acbuild.go:123 +0x73
    github.com/appc/acbuild/Godeps/_workspace/src/github.com/spf13/cobra.(*Command).execute(0xd19fc0, 0xc820062f00, 0x5, 0x5, 0x0, 0x0)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/spf13/cobra/command.go:496 +0x6e3
    github.com/appc/acbuild/Godeps/_workspace/src/github.com/spf13/cobra.(*Command).Execute(0xd17c00, 0x0, 0x0)
            /opt/acbuild/gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/spf13/cobra/command.go:561 +0x180
    main.main()
            /opt/acbuild/gopath/src/github.com/appc/acbuild/acbuild/acbuild.go:198 +0x94
    
    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
            /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
    
    goroutine 19 [select]:
    net/http.(*persistConn).writeLoop(0xc8200d33f0)
            /usr/local/go/src/net/http/transport.go:1009 +0x40c
    created by net/http.(*Transport).dialConn
            /usr/local/go/src/net/http/transport.go:686 +0xc9d
    
    goroutine 21 [IO wait]:
    net.runtime_pollWait(0x7fd040647120, 0x72, 0xc8200121b0)
            /usr/local/go/src/runtime/netpoll.go:157 +0x60
    net.(*pollDesc).Wait(0xc8200aced0, 0x72, 0x0, 0x0)
            /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
    net.(*pollDesc).WaitRead(0xc8200aced0, 0x0, 0x0)
            /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
    net.(*netFD).Read(0xc8200ace70, 0xc820458000, 0x8000, 0x8000, 0x0, 0x7fd040641050, 0xc8200121b0)
            /usr/local/go/src/net/fd_unix.go:232 +0x23a
    net.(*conn).Read(0xc82015e018, 0xc820458000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
            /usr/local/go/src/net/net.go:172 +0xe4
    crypto/tls.(*block).readFromUntil(0xc820424ff0, 0x7fd0406472a0, 0xc82015e018, 0x5, 0x0, 0x0)
            /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
    crypto/tls.(*Conn).readRecord(0xc8201b5b80, 0x99c017, 0x0, 0x0)
            /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
    crypto/tls.(*Conn).Read(0xc8201b5b80, 0xc820456000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            /usr/local/go/src/crypto/tls/conn.go:901 +0x167
    net/http.noteEOFReader.Read(0x7fd03edcf960, 0xc8201b5b80, 0xc8200d34f8, 0xc820456000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            /usr/local/go/src/net/http/transport.go:1370 +0x67
    net/http.(*noteEOFReader).Read(0xc820442b60, 0xc820456000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            <autogenerated>:126 +0xd0
    bufio.(*Reader).fill(0xc8203f30e0)
            /usr/local/go/src/bufio/bufio.go:97 +0x1e9
    bufio.(*Reader).Peek(0xc8203f30e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
            /usr/local/go/src/bufio/bufio.go:132 +0xcc
    net/http.(*persistConn).readLoop(0xc8200d34a0)
            /usr/local/go/src/net/http/transport.go:876 +0xf7
    created by net/http.(*Transport).dialConn
            /usr/local/go/src/net/http/transport.go:685 +0xc78
    
    goroutine 18 [IO wait]:
    net.runtime_pollWait(0x7fd0406471e0, 0x72, 0xc8200121b0)
            /usr/local/go/src/runtime/netpoll.go:157 +0x60
    net.(*pollDesc).Wait(0xc8200acd10, 0x72, 0x0, 0x0)
            /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
    net.(*pollDesc).WaitRead(0xc8200acd10, 0x0, 0x0)
            /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
    net.(*netFD).Read(0xc8200accb0, 0xc820134000, 0x1000, 0x1000, 0x0, 0x7fd040641050, 0xc8200121b0)
            /usr/local/go/src/net/fd_unix.go:232 +0x23a
    net.(*conn).Read(0xc8200281e0, 0xc820134000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            /usr/local/go/src/net/net.go:172 +0xe4
    crypto/tls.(*block).readFromUntil(0xc820128000, 0x7fd0406472a0, 0xc8200281e0, 0x5, 0x0, 0x0)
            /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
    crypto/tls.(*Conn).readRecord(0xc82007e840, 0x99c017, 0x0, 0x0)
            /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
    crypto/tls.(*Conn).Read(0xc82007e840, 0xc820135000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            /usr/local/go/src/crypto/tls/conn.go:901 +0x167
    net/http.noteEOFReader.Read(0x7fd03edcf960, 0xc82007e840, 0xc8200d3448, 0xc820135000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            /usr/local/go/src/net/http/transport.go:1370 +0x67
    net/http.(*noteEOFReader).Read(0xc820423f40, 0xc820135000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            <autogenerated>:126 +0xd0
    bufio.(*Reader).fill(0xc8203f29c0)
            /usr/local/go/src/bufio/bufio.go:97 +0x1e9
    bufio.(*Reader).Peek(0xc8203f29c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
            /usr/local/go/src/bufio/bufio.go:132 +0xcc
    net/http.(*persistConn).readLoop(0xc8200d33f0)
            /usr/local/go/src/net/http/transport.go:876 +0xf7
    created by net/http.(*Transport).dialConn
            /usr/local/go/src/net/http/transport.go:685 +0xc78
    
    goroutine 22 [select]:
    net/http.(*persistConn).writeLoop(0xc8200d34a0)
            /usr/local/go/src/net/http/transport.go:1009 +0x40c
    created by net/http.(*Transport).dialConn
            /usr/local/go/src/net/http/transport.go:686 +0xc9d

Running git bisect points to the following commit:

    a5ad61df3b0d636115d3543c82befc0c84ffdb48 is the first bad commit
    commit a5ad61df3b0d636115d3543c82befc0c84ffdb48
    Author: Derek Gonyeo <derek.gonyeo@coreos.com>
    Date:   Mon Oct 19 18:04:15 2015 -0700
    
        *: refactored library functions, added struct with common fields
        
        The library was refactored so that all the exposed functions were
        attached to a struct containing the information about the current
        context. This makes using the library much cleaner.
        
        The Registry struct had some of its fields renamed to be consistent with
        the new struct in the library.
        
        The functions for acquiring and releasing the lock were also moved from
        acbuild/acbuild.go to the new struct.
    
    :040000 040000 0b4c18665811cff0026264baf86df63fafcc05ee 55039ab1fead9942c9614bbbe9f739b6f657cf0d M	acbuild
    :040000 040000 a0e24013e636d4e8189af2c8d6d87acb0f914996 ce69a0ba1fd044cde549f7320f8aeef1f6ca40ee M	lib
    :040000 040000 3a03acbd4d502a348d419705fb0f1257906a7060 d0ac54b87df26184a5bc3c884b8bc8c36fa50363 M	registry

**Comment by dgonyeo** [comment]
Sorry about that! There's two things at play here:
- There's a bug in the github.com/coreos/ioprogress library that I [fixed a couple week ago](https://github.com/coreos/ioprogress/pull/5), but it appears that it's languishing in code review.
- The logic for the numbers to draw in the uncompressing progress bar that's enabled with the `--debug` flag isn't correct, and the refactor commit you're on changed it so that the `--debug` flag is properly passed through to the part of the code that draws this. I'll disable that for now.

**Comment by dgonyeo** [comment]
I've got a pull request in to fix this, but until that gets merged if you remove the `--debug` flag from the run command that should be a viable workaround.

**Comment by jcollie** [comment]
Thanks for taking care of this so quickly!
