### ISSUE TITLE
Use available acibuilder/fsdiffer?

### ISSUE THREAD

**Issue by sgotti** [appc/acbuild#6]
In coreos/rkt#434 I proposed an aci builder library (you can find it here https://github.com/sgotti/acibuilder https://github.com/sgotti/fsdiffer). Maybe it can be improved to support also overlayfs and be used here (no need to vendor, just take it!)

**Comment by jonboulle** [comment]
Per OOB discussion, I suggested @dgonyeo incorporate fsdiffer using a [subtree merge](http://stackoverflow.com/a/8396318) and we can go from there.

**Comment by dgonyeo** [comment]
Closed via https://github.com/appc/acbuild/pull/104
