### ISSUE TITLE
Concurrent build issues

### ISSUE THREAD

**Issue by ecnahc515** [appc/acbuild#67]
If I'm invoking two acbuilds acbuild where the first is using `begin` and the second is using `--modify`, the second one fails to start because the lock for the first is created in the current directory, and the second cannot acquire the lock.

It would be great if the `.acbuild` context was named after the build, and the lock was associated with a particular `.acbuild` context (or aci if using `--modify`).

Ex:
`acbuild begin path/to/example.aci --name example-app` where --name must be unique for this particular build, to allow for multiple concurrent builds.
This would result in something like:
`.acbuild-example-app` and a lock named `.acbuild-example-app.lock` in the current directory.

`acbuild --modiy path/to/example.aci set name coreos.com/example` could produce a lock named something like:
`.path_to_example.aci.lock`

You could still only have one instance of an `acbuild begin` in a single directory, but you could have as many `acbuild --modify` running in the same directory, assuming each have their own ACI to modify (still limited to one acbuild per aci).

**Comment by dgonyeo** [comment]
I suppose I should create a temp directory for --modify builds

**Comment by dgonyeo** [comment]
Now that I've taken a look at this, the issue is actually sillier than I originally thought. `acbuild` does make a temp directory, which is used by `begin`, `write`, and `end`, but it's not used by the given command you want to run.
