### ISSUE TITLE
fails to unmount bind mount

### ISSUE THREAD

**Issue by jcollie** [appc/acbuild#93]
Occasionally when running acbuild I'll get an error like this:

    umount: /home/jcollie/dev/rkt-logstash/.acbuild/target: target is busy
            (In some cases useful info about processes that
             use the device is found by lsof(8) or fuser(1).)

Once that happens and subsequent commands fail with:

    run: remove .acbuild/target/tmp: directory not empty

It doesn't happen every time (maybe 5-10% of the time).

**Comment by dgonyeo** [comment]
Once this happens and `acbuild` exits, are you able to run `umount .acbuild/target` without error?

**Comment by jcollie** [comment]
Yes, I unmount .acbuild/target and then run acbuild end and everything gets cleaned up.

**Comment by dgonyeo** [comment]
Ok, I feel like there's some race condition resulting in umount running before systemd-nspawn is fully done in the directory. I'll poke around, thanks for reporting this.

**Comment by dgonyeo** [comment]
I assume you're using `acbuild run` when you encounter this. What command are you calling? I can't seem to get this to happen with a `while true; do sudo acbuild run ls; done`.

**Comment by jcollie** [comment]
Here's the script that I'm running to build my ACI:

http://fpaste.org/287028/75556144/

I put the sleeps in to help mitigate the problem but it doesn't always help.  I used to install all of the plugins as a separate acbuild run for each plugin before I realized that I could install them all in one shot.  I don't recall it breaking on anything but an acbuild run command.

I'm using Fedora 23 which comes with systemd 222.

**Comment by dgonyeo** [comment]
I'm still having issues reproducing this. I switched from exec'ing the `umount` command to having the acbuild process send the syscall itself, which is something that I should've done in the first place. Maybe this will help fix your issue?

I've just submitted a PR for this (https://github.com/appc/acbuild/pull/94), would you be willing to give the changes a try and see if the error still occurs?

You can pull the new commit from [here](https://github.com/dgonyeo/acbuild/tree/fix-umount), if you'd prefer to avoid waiting for it to get into master.

**Comment by jcollie** [comment]
I haven't had a chance to try the change, but I'm starting to suspect a 3rd party... I use syncthing to sync this directory between my work desktop and my laptop and I think that may be getting in the way here.  I'll be out on vacation for the next week so I don't know if I'll get a chance to do any more testing before I get back.

**Comment by dgonyeo** [comment]
Ok, no rush. If this is an issue with acbuild, either someone else will come along in the interim with the issue who can test things for me, or it's not affecting very many people.

**Comment by jonboulle** [comment]
@dgonyeo Another option to explore is to use `--overlay` on modern versions of `systemd-nspawn` which would potentially mean we can avoid doing any of the mounting ourselves. (This could kind of go in hand with #86 in that we would provide a controlled/known-good version of nspawn)

**Comment by jcollie** [comment]
OK, back from vacation and had some time to test.  The problem was definitely caused by the file sync software (Syncthing).  After shutting down Syncthing I can no longer reproduce.
