### ISSUE TITLE
Please "vendor" released/tagged dependencies whenever possible

### ISSUE THREAD

**Issue by onlyjob** [appc/acbuild#98]
Downstream package maintainers should be able to reuse packages that are usually built from released/tagged versions instead of random snapshot.

Whenever possible please bundle (vendor) released/tagged versions of components in `Godeps`. Thanks.

**Comment by jonboulle** [comment]
I don't really understand your question - we do vendor dependencies right now https://github.com/appc/acbuild/blob/master/Godeps/Godeps.json - no?

**Comment by onlyjob** [comment]
Yes but bundled (vendored) version of _github.com/appc/spec_ is ahead of latest [release](https://github.com/appc/spec/releases). Presumably releases are suppose to be API-stable so vendoring random snapshot of "master" is not nice.

**Comment by dgonyeo** [comment]
This is something I'll be interested in enforcing once acbuild comes a little farther along.

At this point in time a lot of its core features are still being created, which often requires patches to its dependencies. I'd prefer to not have acbuild development blocking on new releases of the appc spec or rkt, but once things become more stable it should be reasonable to stick to tagged releases of dependencies.

**Comment by onlyjob** [comment]
Precisely. In this particular case I've noticed that _acbuild v0.1.1_ uses/requires unreleased snapshot of _appc/spec_ which is not compatible with its latest release. IMHO for _specification_ is even more important to stick to formal release than for ordinary library... There is no need to slow down development but release process needs to ensure that latest (formal, tagged) release of _acbuild_ is based upon formal release of appc specification and other libraries.

**Comment by dgonyeo** [comment]
acbuild should now be vendoring a tagged version of both rkt (v1.2.0) and the appc spec (v0.7.4), so I'm going to close this.

**Comment by onlyjob** [comment]
Thanks. :)

**Comment by onlyjob** [comment]
Perhaps it would be a good time to tag new release of _acbuild_.

**Comment by dgonyeo** [comment]
There's a few more things I'd like to get wrapped up before doing so. I've got a milestone for it:
https://github.com/appc/acbuild/milestones/v0.3.0
